# Generated by Django 4.1.7 on 2023-03-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0001_initial'),
        ('Books', '0002_follow_book_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='books', to='Genres.genre'),
        ),
    ]
