# Generated by Django 4.1.7 on 2023-03-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_alter_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher_company',
            field=models.CharField(default='Freelancer Work', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(null=True),
        ),
    ]
