# Generated by Django 4.1.7 on 2023-03-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_follow_book_follows'),
        ('Copies', '0002_borrow_copy_borrows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_copy', to='Books.book'),
        ),
    ]
