# Generated by Django 4.1.7 on 2023-03-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Copies', '0003_alter_copy_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='borrow_amount',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='total_amount',
        ),
    ]
