# Generated by Django 4.1.7 on 2023-03-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copies', '0004_remove_copy_borrow_amount_remove_copy_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
