# Generated by Django 4.1.7 on 2023-03-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Copies', '0005_copy_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='name',
        ),
    ]
