# Generated by Django 4.1.7 on 2023-03-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copies', '0006_remove_copy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='teste',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
