# Generated by Django 4.1.7 on 2023-03-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copies', '0008_copy_borrow_amount_copy_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
