# Generated by Django 4.1.7 on 2023-03-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Copies", "0010_remove_copy_teste"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrow",
            name="returned",
            field=models.BooleanField(default=False),
        ),
    ]
