# Generated by Django 4.1.7 on 2023-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Copies", "0011_borrow_returned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copy",
            name="borrow_amount",
        ),
        migrations.RemoveField(
            model_name="copy",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="copy",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
