# Generated by Django 4.1.7 on 2023-03-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Copies", "0012_remove_copy_borrow_amount_remove_copy_total_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrow",
            name="book_id",
            field=models.IntegerField(default=None),
        ),
    ]
