# Generated by Django 4.1.7 on 2023-03-10 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Copies", "0013_borrow_book_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrow",
            old_name="book_id",
            new_name="book",
        ),
    ]
