# Generated by Django 4.1.7 on 2023-03-10 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Copies", "0014_rename_book_id_borrow_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrow",
            old_name="book",
            new_name="id_book",
        ),
    ]
